services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      args:
        CKAN_POSTGRES_DB: ckan_test
        CKAN_DATASTORE_POSTGRES_DB: datastore_test
        CKAN_POSTGRES_USER: ckan_default
        CKAN_DATASTORE_POSTGRES_READ_USER: datastore_read
        CKAN_DATASTORE_POSTGRES_WRITE_USER: datastore_write
        CKAN_POSTGRES_PWD: pass
        CKAN_DATASTORE_POSTGRES_READ_PWD: pass
        CKAN_DATASTORE_POSTGRES_WRITE_PWD: pass
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      # PGDATA: /var/lib/postgresql/data/pgdata
    #volumes:
    #  - ./postgres:/var/lib/postgresql/data
      # - .devcontainer/postgres-docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  solr:
    container_name: solr
    image: opendatacanada/solr
    #image: ckan/ckan-solr:2.9-solr8
    volumes:
      - ./solr:/var/solr/data
    ports:
      - "8983:8983"

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - "6379:6379"

  datapusher:
    container_name: datapusher
    image: ckan/ckan-base-datapusher:0.0.19

  ckan:
    container_name: ckan
    build:
      context: .
      args:
        PGHOST: postgres
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: pass
        PGDATABASE: postgres
    depends_on:
      - postgres
      - solr
      - redis
      - datapusher
    ports:
      - "5001:5000"
    environment:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan_registry
      CKAN_REDIS_URL: redis://redis:6379/1
        #volumes:
        #  - ./ckan:/srv
        #  - ./workspace:/workspace

volumes:
  pg_data:
  solr_data:
