services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ckan
      POSTGRES_PASSWORD: ckan
      POSTGRES_DB: ckan
    volumes:
      - pg_data:/var/lib/postgresql/data
      - .devcontainer/postgres-docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  solr:
    image: ckan/ckan-solr:2.9-solr8
    volumes:
      - solr_data:/opt/solr/server/solr/ckan
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ckan

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  datapusher:
    image: ckan/ckan-base-datapusher:0.0.19

  ckan:
    build: .
    depends_on:
      - db
      - solr
      - redis
      - datapusher 
    ports:
      - "5000:5000"
    environment:
      CKAN_SQLALCHEMY_URL: postgresql://ckan:ckan@db/ckan
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1
      CKAN_SITE_URL: http://localhost:5000

volumes:
  pg_data:
  solr_data: